print("Enter 2 dates ")
print("Ist dates")
y=int(input("Year :"))
m=int(input("Month :"))
d=int(input("Day :"))
print("2nd dates")
y2=int(input("Year :"))
m2=int(input("Month :"))
d2=int(input("Day :"))

print(f"No. of days betweeen 2 dates : {d}")